version: '3.8'

services:
  frontend:
    build:
      context: ./front
      args:
        NODE_ENV: ${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${FRONT_PORT}:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "${BACK_PORT}:3000"
    environment:
      - DB_HOST=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
