version: "3"

services:
  postgres:
    image: postgres:15
    container_name: sonarqube-postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - /home/root/data/postgres:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /home/root/data/sonarqube:/opt/sonarqube/data
      - /home/root/sonarqube/ext:/opt/sonarqube/extensions
      - /home/root/logs/sonarqube:/opt/sonarqube/logs
  jenkins:
    build:
      context: ./jenkins
    image: jenkins-custom
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /var/www/staging:/var/www/staging
      - /var/www/production:/var/www/production
    networks:
      - jenkins-net
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  jenkins-net: