CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    timecreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    timeupdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
