# Utilise une image Node officielle
FROM node:20

# Crée et utilise un répertoire dans le conteneur
WORKDIR /app

# Copie les fichiers de ton projet
COPY package*.json ./
RUN npm install

COPY . .

# Expose le port (si ton app écoute sur 3000)
EXPOSE 3000

# Démarre l'app
CMD ["node", "app.js"]